### ISSUE TITLE
circleci/tests: flaky TestThreads/AddPeer

### ISSUE THREAD

**Issue by jsign** [textileio/go-textile-threads#153]
We're having some problems with `TestThreads/AddPeer` which seems to be failing. I quickly skimmed the code and didn't see anything noticeable. Locally, these tests pass correctly... so maybe is a CircleCI thing.

@sanderpick , I don't know if you have some idea... but maybe using default ports instead of fixed ones might help, since tests in packages tests run on parallel. It might be quite brittle.
Considering this worked for quite a long time, I guess some new tests is making this more probable to fail?

**Comment by sanderpick** [comment]
I'll take a look.
